[[CURRENCIES]]
code="TITI"
issuer="GDEVAMCKOG5E3I2HCT7JFS7NUBJU7J53ALMLDEHDVFF346DCWRWP35AP"
name="TiTi"
desc="TiTi Marketplace Token for Pi Network."
image="https://muasam.titi.onl/banners/3D035BE4-0822-403D-9631-6C4CF674A519.png"